workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment : 
            flutter: stable
        scripts: 
            - name: Installing Dependencies
              script: flutter pub get
            - name: Testing for Modularization Movies
              working_directory: movies
              script: flutter test --coverage
            - name: Testing for Modularization Tv Series
              working_directory: tv_series
              script: flutter test --coverage
            - name: Testing for Modularization Core
              working_directory: core
              script: flutter test --coverage
            - name: Building Android
              script: flutter build appbundle --release
        artifacts:
          - build/**/outputs/apk/**/*.apk
        triggering:
          events: 
            - push 